#!/bin/bash

ChangePassword_Function() {
    local usernameVAR passwordVAR
    local INPUT_TITLE="Change User Password"

    # 1. Get Required Input: Username
    usernameVAR=$(whiptail --inputbox "Type the User name to change password for:" 8 45 "" --title "$INPUT_TITLE" 3>&1 1>&2 2>&3)
    exitstatus=$?

    if [ $exitstatus -ne 0 ] || [ -z "$usernameVAR" ]; then
        whiptail --msgbox "Operation cancelled or username is empty." 8 40 --title "Error"
        return 1
    fi

    # Check if user exists (using 'id -u' which returns non-zero if user not found)
    id $usernameVAR
    if [ $? -ne 0 ]; then
        whiptail --msgbox "Error: User '$usernameVAR' does not exist." 8 50 --title "Error"
        return 1
    fi

    # 2. Execute Password Change
    whiptail --msgbox "You will now be prompted to enter the new password for user '$usernameVAR' in the console below." 8 60 --title "$INPUT_FILE"
    passwordVAR=$(whiptail --passwordbox "Type your new password" 8 78 --title "$INPUT_TITLE" 3>&1 1>&2 2>&3)
    echo $passwordVAR |  sudo passwd $usernameVAR  --stdin

    if [ $? -eq 0 ]; then
        whiptail --msgbox "Password set successfully for $usernameVAR." 8 50 --title "Success"
    else
        whiptail --msgbox "Failed to set password." 8 50 --title "Failure"
    fi
}
